using FladeUp_API.Models.Nationality;

namespace FladeUp_API.Constants
{
    public static class Nationality
    {
        public static List<NationalityModel> All = new()
        {
            new NationalityModel { Id = 1, NameEn = "Afghan", NameUk = "Афганець" },
            new NationalityModel { Id = 2, NameEn = "Albanian", NameUk = "Албанець" },
            new NationalityModel { Id = 3, NameEn = "Algerian", NameUk = "Алжирець" },
            new NationalityModel { Id = 4, NameEn = "Andorran", NameUk = "Андоррець" },
            new NationalityModel { Id = 5, NameEn = "Angolan", NameUk = "Анголець" },
            new NationalityModel { Id = 6, NameEn = "Antiguans and Barbudans", NameUk = "Антигуа і Барбуда" },
            new NationalityModel { Id = 7, NameEn = "Argentinean", NameUk = "Аргентинець" },
            new NationalityModel { Id = 8, NameEn = "Armenian", NameUk = "Вірменець" },
            new NationalityModel { Id = 9, NameEn = "Australian", NameUk = "Австралієць" },
            new NationalityModel { Id = 10, NameEn = "Austrian", NameUk = "Австрієць" },
            new NationalityModel { Id = 11, NameEn = "Azerbaijani", NameUk = "Азербайджанець" },
            new NationalityModel { Id = 12, NameEn = "Bahamian", NameUk = "Багамець" },
            new NationalityModel { Id = 13, NameEn = "Bahraini", NameUk = "Бахрейнець" },
            new NationalityModel { Id = 14, NameEn = "Bangladeshi", NameUk = "Бангладешець" },
            new NationalityModel { Id = 15, NameEn = "Barbadian", NameUk = "Барбадосець" },
            new NationalityModel { Id = 16, NameEn = "Belarusian", NameUk = "Білорус" },
            new NationalityModel { Id = 17, NameEn = "Belgian", NameUk = "Бельгієць" },
            new NationalityModel { Id = 18, NameEn = "Belizean", NameUk = "Белізець" },
            new NationalityModel { Id = 19, NameEn = "Beninese", NameUk = "Бенінець" },
            new NationalityModel { Id = 20, NameEn = "Bhutanese", NameUk = "Бутанець" },
            new NationalityModel { Id = 21, NameEn = "Bolivian", NameUk = "Болівієць" },
            new NationalityModel { Id = 22, NameEn = "Bosnian and Herzegovinian", NameUk = "Боснійець і Герцеговінець" },
            new NationalityModel { Id = 23, NameEn = "Botswanan", NameUk = "Ботсванець" },
            new NationalityModel { Id = 24, NameEn = "Brazilian", NameUk = "Бразилець" },
            new NationalityModel { Id = 25, NameEn = "British", NameUk = "Британець" },
            new NationalityModel { Id = 26, NameEn = "Bruneian", NameUk = "Брунейць" },
            new NationalityModel { Id = 27, NameEn = "Bulgarian", NameUk = "Болгарин" },
            new NationalityModel { Id = 28, NameEn = "Burkinabe", NameUk = "Буркінець" },
            new NationalityModel { Id = 29, NameEn = "Burmese", NameUk = "Бірманець" },
            new NationalityModel { Id = 30, NameEn = "Burundian", NameUk = "Бурундець" },
            new NationalityModel { Id = 31, NameEn = "Cambodian", NameUk = "Камбоджанець" },
            new NationalityModel { Id = 32, NameEn = "Cameroonian", NameUk = "Камерунець" },
            new NationalityModel { Id = 33, NameEn = "Canadian", NameUk = "Канадець" },
            new NationalityModel { Id = 34, NameEn = "Cape Verdean", NameUk = "Кабо-Вердець" },
            new NationalityModel { Id = 35, NameEn = "Central African", NameUk = "Центральноафриканець" },
            new NationalityModel { Id = 36, NameEn = "Chadian", NameUk = "Чадець" },
            new NationalityModel { Id = 37, NameEn = "Chilean", NameUk = "Чилієць" },
            new NationalityModel { Id = 38, NameEn = "Chinese", NameUk = "Китаєць" },
            new NationalityModel { Id = 39, NameEn = "Colombian", NameUk = "Колумбієць" },
            new NationalityModel { Id = 40, NameEn = "Comoran", NameUk = "Коморець" },
            new NationalityModel { Id = 41, NameEn = "Congolese", NameUk = "Конголезець" },
            new NationalityModel { Id = 42, NameEn = "Costa Rican", NameUk = "Коста-Ріканець" },
            new NationalityModel { Id = 43, NameEn = "Croatian", NameUk = "Хорват" },
            new NationalityModel { Id = 44, NameEn = "Cuban", NameUk = "Кубинець" },
            new NationalityModel { Id = 45, NameEn = "Cypriot", NameUk = "Кіпрець" },
            new NationalityModel { Id = 46, NameEn = "Czech", NameUk = "Чех" },
            new NationalityModel { Id = 47, NameEn = "Danish", NameUk = "Данець" },
            new NationalityModel { Id = 48, NameEn = "Djiboutian", NameUk = "Джібутійць" },
            new NationalityModel { Id = 49, NameEn = "Dominican", NameUk = "Домініканець" },
            new NationalityModel { Id = 50, NameEn = "Dutch", NameUk = "Голландець" },
            new NationalityModel { Id = 51, NameEn = "Ecuadorean", NameUk = "Еквадорець" },
            new NationalityModel { Id = 52, NameEn = "Egyptian", NameUk = "Єгиптянин" },
            new NationalityModel { Id = 53, NameEn = "Emirian", NameUk = "Еміратець" },
            new NationalityModel { Id = 54, NameEn = "Equatorial Guinean", NameUk = "Гвінейський екваторіалець" },
            new NationalityModel { Id = 55, NameEn = "Eritrean", NameUk = "Еритреєць" },
            new NationalityModel { Id = 56, NameEn = "Estonian", NameUk = "Естонець" },
            new NationalityModel { Id = 57, NameEn = "Ethiopian", NameUk = "Ефіопець" },
            new NationalityModel { Id = 58, NameEn = "Fijian", NameUk = "Фіджійський" },
            new NationalityModel { Id = 59, NameEn = "Filipino", NameUk = "Філіппінець" },
            new NationalityModel { Id = 60, NameEn = "Finnish", NameUk = "Фін" },
            new NationalityModel { Id = 61, NameEn = "French", NameUk = "Француз" },
            new NationalityModel { Id = 62, NameEn = "Gabonese", NameUk = "Габонець" },
            new NationalityModel { Id = 63, NameEn = "Gambian", NameUk = "Гамбієць" },
            new NationalityModel { Id = 64, NameEn = "Georgian", NameUk = "Грузин" },
            new NationalityModel { Id = 65, NameEn = "German", NameUk = "Німець" },
            new NationalityModel { Id = 66, NameEn = "Ghanaian", NameUk = "Ганець" },
            new NationalityModel { Id = 67, NameEn = "Greek", NameUk = "Грек" },
            new NationalityModel { Id = 68, NameEn = "Grenadian", NameUk = "Гренадець" },
            new NationalityModel { Id = 69, NameEn = "Guatemalan", NameUk = "Гватемальць" },
            new NationalityModel { Id = 70, NameEn = "Guinea-Bissauan", NameUk = "Гвінейський бісауцець" },
            new NationalityModel { Id = 71, NameEn = "Guinean", NameUk = "Гвінейський" },
            new NationalityModel { Id = 72, NameEn = "Guyanese", NameUk = "Гаянець" },
            new NationalityModel { Id = 73, NameEn = "Haitian", NameUk = "Гаїтянин" },
            new NationalityModel { Id = 74, NameEn = "Herzegovinian", NameUk = "Герцеговінець" },
            new NationalityModel { Id = 75, NameEn = "Honduran", NameUk = "Гондурасець" },
            new NationalityModel { Id = 76, NameEn = "Hungarian", NameUk = "Угорець" },
            new NationalityModel { Id = 77, NameEn = "I-Kiribati", NameUk = "Кірибаті" },
            new NationalityModel { Id = 78, NameEn = "Icelander", NameUk = "Ісландець" },
            new NationalityModel { Id = 79, NameEn = "Indian", NameUk = "Індієць" },
            new NationalityModel { Id = 80, NameEn = "Indonesian", NameUk = "Індонезієць" },
            new NationalityModel { Id = 81, NameEn = "Iranian", NameUk = "Іранець" },
            new NationalityModel { Id = 82, NameEn = "Iraqi", NameUk = "Іракець" },
            new NationalityModel { Id = 83, NameEn = "Irish", NameUk = "Ірландець" },
            new NationalityModel { Id = 84, NameEn = "Israeli", NameUk = "Ізраїльтянин" },
            new NationalityModel { Id = 85, NameEn = "Italian", NameUk = "Італієць" },
            new NationalityModel { Id = 86, NameEn = "Ivorian", NameUk = "Кот-д'Івуарець" },
            new NationalityModel { Id = 87, NameEn = "Jamaican", NameUk = "Ямайський" },
            new NationalityModel { Id = 88, NameEn = "Japanese", NameUk = "Японець" },
            new NationalityModel { Id = 89, NameEn = "Jordanian", NameUk = "Йорданець" },
            new NationalityModel { Id = 90, NameEn = "Kazakhstani", NameUk = "Казах" },
            new NationalityModel { Id = 91, NameEn = "Kenyan", NameUk = "Кенієць" },
            new NationalityModel { Id = 92, NameEn = "Kittian and Nevisian", NameUk = "Кітті і Невіс" },
            new NationalityModel { Id = 93, NameEn = "Kuwaiti", NameUk = "Кувейтець" },
            new NationalityModel { Id = 94, NameEn = "Kyrgyz", NameUk = "Киргиз" },
            new NationalityModel { Id = 95, NameEn = "Laotian", NameUk = "Лаосець" },
            new NationalityModel { Id = 96, NameEn = "Latvian", NameUk = "Латвієць" },
            new NationalityModel { Id = 97, NameEn = "Lebanese", NameUk = "Ліванець" },
            new NationalityModel { Id = 98, NameEn = "Liberian", NameUk = "Ліберієць" },
            new NationalityModel { Id = 99, NameEn = "Libyan", NameUk = "Лівієць" },
            new NationalityModel { Id = 100, NameEn = "Liechtensteiner", NameUk = "Ліхтенштейнець" },
            new NationalityModel { Id = 101, NameEn = "Lithuanian", NameUk = "Литовець" },
            new NationalityModel { Id = 102, NameEn = "Luxembourger", NameUk = "Люксембуржець" },
            new NationalityModel { Id = 103, NameEn = "Macedonian", NameUk = "Македонець" },
            new NationalityModel { Id = 104, NameEn = "Malagasy", NameUk = "Малагасієць" },
            new NationalityModel { Id = 105, NameEn = "Malawian", NameUk = "Малавійський" },
            new NationalityModel { Id = 106, NameEn = "Malaysian", NameUk = "Малайзієць" },
            new NationalityModel { Id = 107, NameEn = "Maldivian", NameUk = "Мальдівець" },
            new NationalityModel { Id = 108, NameEn = "Malian", NameUk = "Малієць" },
            new NationalityModel { Id = 109, NameEn = "Maltese", NameUk = "Мальтієць" },
            new NationalityModel { Id = 110, NameEn = "Marshallese", NameUk = "Маршаллець" },
            new NationalityModel { Id = 111, NameEn = "Mauritanian", NameUk = "Мавританець" },
            new NationalityModel { Id = 112, NameEn = "Mauritian", NameUk = "Маврикієць" },
            new NationalityModel { Id = 113, NameEn = "Mexican", NameUk = "Мексиканець" },
            new NationalityModel { Id = 114, NameEn = "Micronesian", NameUk = "Мікронезієць" },
            new NationalityModel { Id = 115, NameEn = "Moldovan", NameUk = "Молдован" },
            new NationalityModel { Id = 116, NameEn = "Monacan", NameUk = "Монакієць" },
            new NationalityModel { Id = 117, NameEn = "Mongolian", NameUk = "Монгол" },
            new NationalityModel { Id = 118, NameEn = "Moroccan", NameUk = "Марокканець" },
            new NationalityModel { Id = 119, NameEn = "Mosotho", NameUk = "Лесото" },
            new NationalityModel { Id = 120, NameEn = "Motswana", NameUk = "Ботсванець" },
            new NationalityModel { Id = 121, NameEn = "Mozambican", NameUk = "Мозамбікієць" },
            new NationalityModel { Id = 122, NameEn = "Namibian", NameUk = "Намібієць" },
            new NationalityModel { Id = 123, NameEn = "Nauruan", NameUk = "Науруанець" },
            new NationalityModel { Id = 124, NameEn = "Nepalese", NameUk = "Непалець" },
            new NationalityModel { Id = 125, NameEn = "New Zealander", NameUk = "Новозеландець" },
            new NationalityModel { Id = 126, NameEn = "Nicaraguan", NameUk = "Нікарагуанець" },
            new NationalityModel { Id = 127, NameEn = "Nigerian", NameUk = "Нігерієць" },
            new NationalityModel { Id = 128, NameEn = "Nigerien", NameUk = "Нігерець" },
            new NationalityModel { Id = 129, NameEn = "North Korean", NameUk = "Північнокорейський" },
            new NationalityModel { Id = 130, NameEn = "Northern Irish", NameUk = "Північноірландець" },
            new NationalityModel { Id = 131, NameEn = "Northern Irish", NameUk = "Північноірландець" },
            new NationalityModel { Id = 132, NameEn = "Norwegian", NameUk = "Норвежець" },
            new NationalityModel { Id = 133, NameEn = "Omani", NameUk = "Оманець" },
            new NationalityModel { Id = 134, NameEn = "Pakistani", NameUk = "Пакистанець" },
            new NationalityModel { Id = 135, NameEn = "Palauan", NameUk = "Палауанець" },
            new NationalityModel { Id = 136, NameEn = "Panamanian", NameUk = "Панамець" },
            new NationalityModel { Id = 137, NameEn = "Papua New Guinean", NameUk = "Папуасець" },
            new NationalityModel { Id = 138, NameEn = "Paraguayan", NameUk = "Парагвайць" },
            new NationalityModel { Id = 139, NameEn = "Peruvian", NameUk = "Перуанець" },
            new NationalityModel { Id = 140, NameEn = "Polish", NameUk = "Поляк" },
            new NationalityModel { Id = 141, NameEn = "Portuguese", NameUk = "Португалець" },
            new NationalityModel { Id = 142, NameEn = "Qatari", NameUk = "Катарець" },
            new NationalityModel { Id = 143, NameEn = "Romanian", NameUk = "Румун" },
            new NationalityModel { Id = 144, NameEn = "Russian", NameUk = "Росіянин" },
            new NationalityModel { Id = 145, NameEn = "Rwandan", NameUk = "Руандієць" },
            new NationalityModel { Id = 146, NameEn = "Saint Lucian", NameUk = "Сент-Люсійський" },
            new NationalityModel { Id = 147, NameEn = "Salvadoran", NameUk = "Сальвадорець" },
            new NationalityModel { Id = 148, NameEn = "Samoan", NameUk = "Самоанець" },
            new NationalityModel { Id = 149, NameEn = "San Marinese", NameUk = "Сан-Марінський" },
            new NationalityModel { Id = 150, NameEn = "Sao Tomean", NameUk = "Сан-Томе і Прінсіпі" },
            new NationalityModel { Id = 151, NameEn = "Saudi", NameUk = "Саудівець" },
            new NationalityModel { Id = 152, NameEn = "Scottish", NameUk = "Шотландець" },
            new NationalityModel { Id = 153, NameEn = "Senegalese", NameUk = "Сенегалець" },
            new NationalityModel { Id = 154, NameEn = "Serbian", NameUk = "Серб" },
            new NationalityModel { Id = 155, NameEn = "Seychellois", NameUk = "Сейшельський" },
            new NationalityModel { Id = 156, NameEn = "Sierra Leonean", NameUk = "Сьєрра-Леонець" },
            new NationalityModel { Id = 157, NameEn = "Singaporean", NameUk = "Сінгапурець" },
            new NationalityModel { Id = 158, NameEn = "Slovak", NameUk = "Словак" },
            new NationalityModel { Id = 159, NameEn = "Slovenian", NameUk = "Словенець" },
            new NationalityModel { Id = 160, NameEn = "Solomon Islander", NameUk = "Соломонець" },
            new NationalityModel { Id = 161, NameEn = "Somali", NameUk = "Сомалієць" },
            new NationalityModel { Id = 162, NameEn = "South African", NameUk = "Південноафриканець" },
            new NationalityModel { Id = 163, NameEn = "South Korean", NameUk = "Південнокорейський" },
            new NationalityModel { Id = 164, NameEn = "Spanish", NameUk = "Іспанець" },
            new NationalityModel { Id = 165, NameEn = "Sri Lankan", NameUk = "Шрі-ланкієць" },
            new NationalityModel { Id = 166, NameEn = "Sudanese", NameUk = "Суданець" },
            new NationalityModel { Id = 167, NameEn = "Surinamer", NameUk = "Суринамець" },
            new NationalityModel { Id = 168, NameEn = "Swazi", NameUk = "Свазі" },
            new NationalityModel { Id = 169, NameEn = "Swedish", NameUk = "Швед" },
            new NationalityModel { Id = 170, NameEn = "Swiss", NameUk = "Швейцарець" },
            new NationalityModel { Id = 171, NameEn = "Syrian", NameUk = "Сирієць" },
            new NationalityModel { Id = 172, NameEn = "Taiwanese", NameUk = "Тайванець" },
            new NationalityModel { Id = 173, NameEn = "Tajik", NameUk = "Таджик" },
            new NationalityModel { Id = 174, NameEn = "Tanzanian", NameUk = "Танзанієць" },
            new NationalityModel { Id = 175, NameEn = "Thai", NameUk = "Таїландець" },
            new NationalityModel { Id = 176, NameEn = "Togolese", NameUk = "Тоголезець" },
            new NationalityModel { Id = 177, NameEn = "Tongan", NameUk = "Тонганець" },
            new NationalityModel { Id = 178, NameEn = "Trinidadian or Tobagonian", NameUk = "Трінідад і Тобаго" },
            new NationalityModel { Id = 179, NameEn = "Tunisian", NameUk = "Тунісець" },
            new NationalityModel { Id = 180, NameEn = "Turkish", NameUk = "Турок" },
            new NationalityModel { Id = 181, NameEn = "Tuvaluan", NameUk = "Тувалуанець" },
            new NationalityModel { Id = 182, NameEn = "Ugandan", NameUk = "Угандієць" },
            new NationalityModel { Id = 183, NameEn = "Ukrainian", NameUk = "Українець" },
            new NationalityModel { Id = 184, NameEn = "Uruguayan", NameUk = "Уругвайць" },
            new NationalityModel { Id = 185, NameEn = "Uzbekistani", NameUk = "Узбек" },
            new NationalityModel { Id = 186, NameEn = "Venezuelan", NameUk = "Венесуелець" },
            new NationalityModel { Id = 187, NameEn = "Vietnamese", NameUk = "В'єтнамець" },
            new NationalityModel { Id = 188, NameEn = "Welsh", NameUk = "Валлієць" },
            new NationalityModel { Id = 189, NameEn = "Yemenite", NameUk = "Єменець" },
            new NationalityModel { Id = 190, NameEn = "Zambian", NameUk = "Замбійський" },
            new NationalityModel { Id = 191, NameEn = "Zimbabwean", NameUk = "Зімбабвійський" }

        };
    }
}
